import React, { createContext, useContext, useState, useCallback } from "react";

const TRANSLATIONS = {
  EN: {
    /* ── Nav / Sidebar ── */
    nav_home:      "Home Page",
    nav_shop:      "Shop the Cars",
    nav_rental:    "Car Rental",
    nav_sold:      "Sold History",
    nav_contact:   "Contact Us",
    nav_help:      "Need Help?",
    nav_dashboard: "Dashboard",
    menu:          "Menu",
    view_profile:  "View your profile",
    login:         "Log In",
    signup:        "Sign Up",
    logout:        "Log Out",
    language:      "Language",
    copyright:     "© BKK Kaung Pyae Auto",

    /* ── Hero ── */
    hero_eyebrow: "Premium cars",
    hero_title:   "For rent and ownership",
    hero_browse:  "Browse Cars →",
    hero_scroll:  "Scroll",

    /* ── Brands ── */
    brands_title:   "Brands",
    view_all:       "View all →",
    loading_brands: "Loading brands...",

    /* ── Car Types ── */
    car_types_title: "Browse by Car Type",
    cars_ready:      "+100 cars are ready to be yours",
    view_on_shop:    "View on Shop →",

    /* ── Deals ── */
    deals_eyebrow:    "Exclusive Collection",
    deals_title:      "Best Deals For You",
    deals_sub:        "Premium vehicles. Unmatched prices.",
    deals_new:        "New Arrivals",
    deals_rented:     "Most Rented",
    deals_loading:    "Loading...",
    deals_shop_now:   "Shop Now",
    deals_flip_front: "Tap card to see specs ↺",
    deals_specs:      "Specs",
    deals_flip_back:  "Tap to go back ↺",
    deals_view_all:   "View Full Collection",

    /* ── Spec labels (shared: Deals + CarDetail) ── */
    spec_year:         "Year",
    spec_engine:       "Engine",
    spec_mileage:      "Mileage",
    spec_fuel:         "Fuel",
    spec_transmission: "Transmission",
    spec_color:        "Color",
    spec_drive:        "Drive",
    spec_seats:        "Seats",

    /* ── Why Choose Us ── */
    wcu_title:   "Why Choose Us?",
    wcu_sub:     "What makes us different",
    wcu_tag1:    "Quality",
    wcu_h4_1:    "Trusted & Well-Maintained Cars",
    wcu_p1:      "Every vehicle is carefully inspected, clean, and ready to drive.",
    wcu_tag2:    "Pricing",
    wcu_h4_2:    "Transparent Pricing",
    wcu_p2:      "Clear price with no hidden fees — what you see is what you pay.",
    wcu_tag3:    "Booking",
    wcu_h4_3:    "Fast & Easy Booking",
    wcu_p3:      "Rent in minutes with flexible rental options and quick support.",
    wcu_btn:     "Buy / Rent a Car →",
    wcu_features:"• Trust  •  Fair Price  •  Simple & Fast Booking",

    /* ── Testimonials ── */
    test_title1:  "What Our",
    test_title2:  "Customers Say",
    test_sub:     "Real experiences · Real drivers",
    test_verified:"verified",
    test_footer:  "Premium service built on trust, quality & simplicity",

    /* ── Sold History ── */
    sold_eyebrow:   "Sales Record",
    sold_title1:    "SOLD",
    sold_title2:    "HISTORY",
    sold_sub:       "Every vehicle that found its new home",
    sold_view_all:  "View All Records →",
    sold_total:     "Total Cars Sold",
    sold_month:     "Sold This Month",
    sold_empty:     "No sold cars found for this filter.",
    sold_badge:     "Sold",
    sold_showing:   "Showing",
    sold_of:        "of",
    sold_records:   "records",

    /* ── Car Detail ── */
    cd_loading:     "Loading...",
    cd_not_found:   "Car not found",
    cd_rental_tag:  "Rental Car",
    cd_sale_tag:    "For Sale",
    cd_specs:       "Specifications",
    cd_details:     "Details",
    cd_7day:        "7-Day Price (5% off)",
    cd_30day:       "30-Day Price (10% off)",
    cd_status:      "Status",
    cd_model_year:  "Model Year",
    cd_vin:         "VIN",
    cd_documents:   "Car Documents",
    cd_terms:       "Rental Terms & Conditions",
    cd_interested:      "Interested in this car? Get in touch with us.",
    cd_contact_btn:     "Contact Us →",
    cd_back:            "← Back to Showroom",
    cd_breadcrumb_shop: "Showroom",
    cd_prev:            "Prev",
    cd_next:            "Next",
    cd_similar:         "You Might Also Like",

    /* ── Showroom ── */
    sr_title:       "Find Your Perfect Car",
    sr_subtitle:    "Explore our curated collection of quality vehicles",
    sr_buy:         "Buy",
    sr_rental:      "Rental",
    sr_search:      "Search brand or model...",
    sr_all:         "All",
    sr_new_arrival: "New Arrival",
    sr_most_rented: "Most Rented",
    sr_loading:     "Loading vehicles…",
    sr_no_results:      "No vehicles found matching your filters.",
    sr_empty_title:     "No vehicles found",
    sr_clear_filters:   "Clear filters",
    sr_vehicle:         "vehicle",
    sr_vehicles:        "vehicles",
    sr_for_sale:        "For Sale",
    sr_for_rent:        "For Rent",
    sr_details:         "Details →",
    sr_add:             "+ Add Car",
    sr_filters:         "Filters",
    sr_sort:            "Sort",
    sr_sort_default:    "Default",
    sr_sort_price_low:  "Price: Low → High",
    sr_sort_price_high: "Price: High → Low",
    sr_sort_newest:     "Newest First",
    sr_fuel:            "Fuel",
    sr_transmission:    "Transmission",

    /* ── Easy Rental ── */
    er_title:        "Easy Car Rental",
    er_sub:          "Rent a car in just a few simple steps",
    er_step:         "Step",
    er_step1_label:  "Browse",
    er_step2_label:  "Sign Up",
    er_step3_label:  "Book",
    er_rent_btn:     "Rental Cars →",
    er_login_h:      "Log In or Create Account",
    er_login_p:      "Create an account with your phone number or email.",
    er_signup:       "Click here to sign up",
    er_logged:       "Already logged in? Continue to the next step.",
    er_next:         "Next step →",
    er_badge:        "• Insured   • Verified   • Ready to Go",

    /* ── Footer ── */
    footer_tagline: "Your trusted car showroom in Bangkok — quality vehicles, transparent pricing.",
    footer_hours:   "Open Daily · 9:00 AM – 9:00 PM",
    footer_links:   "Quick Links",
    footer_contact: "Contact Us",
    footer_made:    "Made with ♥ in Bangkok",
    footer_rights:  "© 2025 BKK Kaung Pyae Co., Ltd. All rights reserved.",
    footer_home:    "Home",
    footer_shop:    "Shop",
    footer_brands:  "Brands",
    footer_rental:  "Rental",
    footer_about:   "About",
  },

  /* ════════════════════════════════════════════════
     MYANMAR (MM)
  ════════════════════════════════════════════════ */
  MM: {
    nav_home:      "မူလစာမျက်နှာ",
    nav_shop:      "ကားများဝယ်ယူ",
    nav_rental:    "ကားငှားရမ်း",
    nav_sold:      "ရောင်းချမှတ်တမ်း",
    nav_contact:   "ဆက်သွယ်ရန်",
    nav_help:      "အကူအညီလိုပါသလား?",
    nav_dashboard: "ဒက်ရှ်ဘုတ်",
    menu:          "မီနူး",
    view_profile:  "ပရိုဖိုင်ကြည့်ရန်",
    login:         "ဝင်ရောက်မည်",
    signup:        "အကောင့်ဖွင့်",
    logout:        "ထွက်မည်",
    language:      "ဘာသာစကား",
    copyright:     "© BKK Kaung Pyae Auto",

    hero_eyebrow: "မြင့်မားသောကားများ",
    hero_title:   "ငှားရမ်းနှင့် ပိုင်ဆိုင်ရန်",
    hero_browse:  "ကားများကြည့်ရှုရန် →",
    hero_scroll:  "ဆင်းရန်",

    brands_title:   "အမှတ်တံဆိပ်များ",
    view_all:       "အားလုံးကြည့်ရန် →",
    loading_brands: "ဖွင့်နေသည်...",

    car_types_title: "ကားအမျိုးအစားဖြင့် ရှာဖွေရန်",
    cars_ready:      "+ကားပေါင်း ၁၀၀ သင့်ကိုစောင့်နေသည်",
    view_on_shop:    "ဆိုင်တွင်ကြည့်ရန် →",

    deals_eyebrow:    "ရွေးချယ်ထားသောစုစည်းမှု",
    deals_title:      "သင့်အတွက် အကောင်းဆုံးဈေးနှုန်းများ",
    deals_sub:        "မြင့်မားသောယာဉ်များ။ မနှိုင်းယှဉ်နိုင်သောဈေးနှုန်းများ။",
    deals_new:        "ကားသစ်များ",
    deals_rented:     "အများဆုံးငှားရမ်း",
    deals_loading:    "ဖွင့်နေသည်...",
    deals_shop_now:   "ယခုဝယ်ရန်",
    deals_flip_front: "ကတ်ကိုနှိပ်ပါ ↺",
    deals_specs:      "သတ်မှတ်ချက်",
    deals_flip_back:  "နောက်သို့ပြန်ရန် ↺",
    deals_view_all:   "အားလုံးကြည့်ရှုရန်",

    spec_year:         "နှစ်",
    spec_engine:       "အင်ဂျင်",
    spec_mileage:      "မိုင်တိုင်",
    spec_fuel:         "လောင်စာ",
    spec_transmission: "ဂီယာ",
    spec_color:        "အရောင်",
    spec_drive:        "မောင်းနှင်မှု",
    spec_seats:        "ထိုင်ခုံ",

    wcu_title:   "ဘာကြောင့် ကျွန်ုပ်တို့ကို ရွေးချယ်ရမလဲ?",
    wcu_sub:     "ကျွန်ုပ်တို့ကိုထူးခြားစေသည်",
    wcu_tag1:    "အရည်အသွေး",
    wcu_h4_1:    "ယုံကြည်ရပြီး ကောင်းမွန်ထိန်းသိမ်းထားသောကားများ",
    wcu_p1:      "ယာဉ်တိုင်းကို သေချာစစ်ဆေးပြီး သန့်ရှင်းကာ မောင်းနှင်ရန်အသင့်ဖြစ်သည်",
    wcu_tag2:    "ဈေးနှုန်း",
    wcu_h4_2:    "ဈေးနှုန်းပွင့်လင်းမြင်သာ",
    wcu_p2:      "လျှို့ဝှက်ဈေးမပါဘဲ ပွင့်လင်းသောဈေးနှုန်း — ကြည့်သည့်ဈေးပဲပေးရမည်",
    wcu_tag3:    "မှာယူ",
    wcu_h4_3:    "လျင်မြန်လွယ်ကူသောမှာယူခြင်း",
    wcu_p3:      "မိနစ်အနည်းငယ်ဖြင့် ကောင်းမွန်သောဝန်ဆောင်မှုနှင့်အတူ မှာယူနိုင်သည်",
    wcu_btn:     "ကား ဝယ်/ငှား →",
    wcu_features:"• ယုံကြည်မှု  •  ဈေးနှုန်းမျှတ  •  လွယ်ကူသောမှာယူ",

    test_title1:  "ကျွန်ုပ်တို့၏",
    test_title2:  "ဝယ်သူများ ပြောဆိုသည်",
    test_sub:     "တကယ့်အတွေ့အကြုံ · တကယ့်ယာဉ်မောင်းများ",
    test_verified:"အတည်ပြုပြီး",
    test_footer:  "ယုံကြည်မှု၊ အရည်အသွေးနှင့် ရိုးရှင်းမှုပေါ်တည်ဆောက်ထားသောဝန်ဆောင်မှု",

    sold_eyebrow:   "ရောင်းချမှတ်တမ်း",
    sold_title1:    "ရောင်းချ",
    sold_title2:    "မှတ်တမ်း",
    sold_sub:       "အသစ်တစ်ဆိုင်ရာရောင်းချသွားသောယာဉ်တိုင်း",
    sold_view_all:  "မှတ်တမ်းအားလုံးကြည့်ရန် →",
    sold_total:     "ရောင်းချပြီးသောကားစုစုပေါင်း",
    sold_month:     "ဤလရောင်းချပြီးသော",
    sold_empty:     "စစ်ထုတ်မှုနှင့်ကိုက်ညီသောရောင်းချကားမတွေ့ပါ",
    sold_badge:     "ရောင်းချပြီး",
    sold_showing:   "ပြသနေသည်",
    sold_of:        "မှ",
    sold_records:   "မှတ်တမ်း",

    cd_loading:     "ဖွင့်နေသည်...",
    cd_not_found:   "ကားမတွေ့ပါ",
    cd_rental_tag:  "ငှားရမ်းကား",
    cd_sale_tag:    "ရောင်းချရန်",
    cd_specs:       "သတ်မှတ်ချက်များ",
    cd_details:     "အသေးစိတ်",
    cd_7day:        "ရက် ၇ ဈေးနှုန်း (၅% လျှော့)",
    cd_30day:       "ရက် ၃၀ ဈေးနှုန်း (၁၀% လျှော့)",
    cd_status:      "အခြေအနေ",
    cd_model_year:  "ကားနှစ်",
    cd_vin:         "VIN",
    cd_documents:   "ကားစာရွက်စာတမ်းများ",
    cd_terms:       "ငှားရမ်းသည့်စည်းမျဉ်းများ",
    cd_interested:      "ဤကားကိုစိတ်ဝင်စားပါသလား? ကျွန်ုပ်တို့ကိုဆက်သွယ်ပါ",
    cd_contact_btn:     "ဆက်သွယ်ရန် →",
    cd_back:            "← Showroom သို့ပြန်",
    cd_breadcrumb_shop: "ကားဆိုင်",
    cd_prev:            "ယခင်",
    cd_next:            "နောက်",
    cd_similar:         "ဆင်တူကားများ",

    sr_title:       "သင့်ကားကိုရှာဖွေပါ",
    sr_subtitle:    "ကျွန်ုပ်တို့၏ ကောင်းမွန်သောယာဉ်များကိုကြည့်ပါ",
    sr_buy:         "ဝယ်ယူ",
    sr_rental:      "ငှားရမ်း",
    sr_search:      "အမှတ်တံဆိပ် သို့ မော်ဒယ်ရှာပါ...",
    sr_all:         "အားလုံး",
    sr_new_arrival: "ကားသစ်",
    sr_most_rented: "အများဆုံးငှားရမ်း",
    sr_loading:     "ယာဉ်များဖွင့်နေသည်...",
    sr_no_results:   "စစ်ထုတ်မှုနှင့်ကိုက်ညီသောယာဉ်မတွေ့ပါ",
    sr_empty_title:  "ယာဉ်မတွေ့ပါ",
    sr_clear_filters:"စစ်ထုတ်မှုဖယ်ရန်",
    sr_vehicle:      "ယာဉ်",
    sr_vehicles:     "ယာဉ်များ",
    sr_for_sale:        "ရောင်းချရန်",
    sr_for_rent:        "ငှားရမ်းရန်",
    sr_details:         "အသေးစိတ် →",
    sr_add:             "+ ကားထည့်ရန်",
    sr_filters:         "စစ်ထုတ်မှု",
    sr_sort:            "စီရှင်း",
    sr_sort_default:    "မူလ",
    sr_sort_price_low:  "ဈေး: နည်း → များ",
    sr_sort_price_high: "ဈေး: များ → နည်း",
    sr_sort_newest:     "အသစ်ဆုံးဦးစွာ",
    sr_fuel:            "လောင်စာ",
    sr_transmission:    "ဂီယာ",

    er_title:        "ကားငှားရမ်းလွယ်ကူ",
    er_sub:          "လွယ်ကူသောအဆင့်အနည်းငယ်ဖြင့် ကားငှားရမ်းနိုင်သည်",
    er_step:         "အဆင့်",
    er_step1_label:  "ကားကြည့်ရန်",
    er_step2_label:  "အကောင့်ဖွင့်",
    er_step3_label:  "မှာယူ",
    er_rent_btn:     "ကားငှားရမ်း →",
    er_login_h:   "အကောင့်ဝင်ရောက် သို့မဟုတ် ဖွင့်ပါ",
    er_login_p:   "ဖုန်းနံပါတ် သို့မဟုတ် အီးမေးနှင့် အကောင့်ဖွင့်ပါ",
    er_signup:    "ဤနေရာတွင် ကိုနှိပ်ပါ",
    er_logged:    "ဝင်ရောက်ပြီးဆိုလျှင် နောက်အဆင့်ကိုဆက်လုပ်နိုင်သည်",
    er_next:      "နောက်အဆင့် →",
    er_badge:     "• အာမခံ   • စစ်ဆေးပြီး   • သင့်ကိုသင်ယူ",

    footer_tagline: "ဘန်ကောက်ရှိ သင်ယုံကြည်ရသောကားဆိုင် — အရည်အသွေးမြင့်ယာဉ်များ",
    footer_hours:   "နေ့တိုင်းဖွင့် · နံနက် ၉ နာရီ – ည ၉ နာရီ",
    footer_links:   "မြန်ဆန်သောဆက်သွယ်ချိတ်",
    footer_contact: "ဆက်သွယ်ရန်",
    footer_made:    "ဘန်ကောက်တွင်ဖန်တီးသည်",
    footer_rights:  "© ၂၀၂၅ BKK Kaung Pyae Co., Ltd.",
    footer_home:    "မူလ",
    footer_shop:    "ဆိုင်",
    footer_brands:  "အမှတ်တံဆိပ်",
    footer_rental:  "ငှားရမ်း",
    footer_about:   "အကြောင်း",
  },

  /* ════════════════════════════════════════════════
     THAI (TH)
  ════════════════════════════════════════════════ */
  TH: {
    nav_home:      "หน้าหลัก",
    nav_shop:      "ซื้อรถยนต์",
    nav_rental:    "เช่ารถยนต์",
    nav_sold:      "ประวัติการขาย",
    nav_contact:   "ติดต่อเรา",
    nav_help:      "ต้องการความช่วยเหลือ?",
    nav_dashboard: "แดชบอร์ด",
    menu:          "เมนู",
    view_profile:  "ดูโปรไฟล์",
    login:         "เข้าสู่ระบบ",
    signup:        "สมัครสมาชิก",
    logout:        "ออกจากระบบ",
    language:      "ภาษา",
    copyright:     "© BKK Kaung Pyae Auto",

    hero_eyebrow: "รถยนต์พรีเมียม",
    hero_title:   "สำหรับเช่าและเป็นเจ้าของ",
    hero_browse:  "ดูรถยนต์ →",
    hero_scroll:  "เลื่อนลง",

    brands_title:   "แบรนด์รถยนต์",
    view_all:       "ดูทั้งหมด →",
    loading_brands: "กำลังโหลด...",

    car_types_title: "เลือกตามประเภทรถ",
    cars_ready:      "รถกว่า 100 คันรอคุณอยู่",
    view_on_shop:    "ดูที่ร้าน →",

    deals_eyebrow:    "คอลเลกชันพิเศษ",
    deals_title:      "ดีลที่ดีที่สุดสำหรับคุณ",
    deals_sub:        "รถยนต์พรีเมียม ราคาที่ไม่มีใครเทียบ",
    deals_new:        "รถใหม่มาถึง",
    deals_rented:     "เช่าบ่อยที่สุด",
    deals_loading:    "กำลังโหลด...",
    deals_shop_now:   "ซื้อเลย",
    deals_flip_front: "แตะการ์ดดูสเปค ↺",
    deals_specs:      "สเปค",
    deals_flip_back:  "แตะเพื่อกลับ ↺",
    deals_view_all:   "ดูคอลเลกชันทั้งหมด",

    spec_year:         "ปี",
    spec_engine:       "เครื่องยนต์",
    spec_mileage:      "ระยะทาง",
    spec_fuel:         "เชื้อเพลิง",
    spec_transmission: "เกียร์",
    spec_color:        "สี",
    spec_drive:        "ระบบขับเคลื่อน",
    spec_seats:        "ที่นั่ง",

    wcu_title:   "ทำไมต้องเลือกเรา?",
    wcu_sub:     "สิ่งที่ทำให้เราแตกต่าง",
    wcu_tag1:    "คุณภาพ",
    wcu_h4_1:    "รถที่น่าเชื่อถือและดูแลอย่างดี",
    wcu_p1:      "รถทุกคันผ่านการตรวจสอบอย่างพิถีพิถัน สะอาด และพร้อมขับ",
    wcu_tag2:    "ราคา",
    wcu_h4_2:    "ราคาโปร่งใส",
    wcu_p2:      "ราคาชัดเจน ไม่มีค่าใช้จ่ายแอบแฝง — เห็นราคาไหนจ่ายราคานั้น",
    wcu_tag3:    "การจอง",
    wcu_h4_3:    "จองเร็วและง่าย",
    wcu_p3:      "เช่าได้ในไม่กี่นาทีพร้อมตัวเลือกที่ยืดหยุ่นและบริการที่รวดเร็ว",
    wcu_btn:     "ซื้อ / เช่า รถ →",
    wcu_features:"• ความเชื่อใจ  •  ราคายุติธรรม  •  จองง่ายรวดเร็ว",

    test_title1:  "สิ่งที่",
    test_title2:  "ลูกค้าพูดถึงเรา",
    test_sub:     "ประสบการณ์จริง · ผู้ขับจริง",
    test_verified:"ยืนยันแล้ว",
    test_footer:  "บริการพรีเมียมที่สร้างบนรากฐานของความไว้วางใจ คุณภาพ และความเรียบง่าย",

    sold_eyebrow:   "บันทึกการขาย",
    sold_title1:    "ประวัติ",
    sold_title2:    "การขาย",
    sold_sub:       "รถทุกคันที่พบบ้านใหม่แล้ว",
    sold_view_all:  "ดูบันทึกทั้งหมด →",
    sold_total:     "รถที่ขายทั้งหมด",
    sold_month:     "ขายเดือนนี้",
    sold_empty:     "ไม่พบรถที่ขายแล้วสำหรับตัวกรองนี้",
    sold_badge:     "ขายแล้ว",
    sold_showing:   "แสดง",
    sold_of:        "จาก",
    sold_records:   "รายการ",

    cd_loading:     "กำลังโหลด...",
    cd_not_found:   "ไม่พบรถ",
    cd_rental_tag:  "รถเช่า",
    cd_sale_tag:    "ขาย",
    cd_specs:       "สเปครถ",
    cd_details:     "รายละเอียด",
    cd_7day:        "ราคา 7 วัน (ลด 5%)",
    cd_30day:       "ราคา 30 วัน (ลด 10%)",
    cd_status:      "สถานะ",
    cd_model_year:  "ปีรุ่น",
    cd_vin:         "VIN",
    cd_documents:   "เอกสารรถ",
    cd_terms:       "เงื่อนไขการเช่า",
    cd_interested:      "สนใจรถคันนี้? ติดต่อเราได้เลย",
    cd_contact_btn:     "ติดต่อเรา →",
    cd_back:            "← กลับโชว์รูม",
    cd_breadcrumb_shop: "โชว์รูม",
    cd_prev:            "ก่อนหน้า",
    cd_next:            "ถัดไป",
    cd_similar:         "รถที่คุณอาจชอบ",

    sr_title:       "ค้นหารถในฝันของคุณ",
    sr_subtitle:    "สำรวจคอลเลกชันรถยนต์คุณภาพของเรา",
    sr_buy:         "ซื้อ",
    sr_rental:      "เช่า",
    sr_search:      "ค้นหายี่ห้อหรือรุ่น...",
    sr_all:         "ทั้งหมด",
    sr_new_arrival: "รถใหม่มาถึง",
    sr_most_rented: "เช่าบ่อยที่สุด",
    sr_loading:     "กำลังโหลดรถ...",
    sr_no_results:   "ไม่พบรถที่ตรงกับตัวกรองของคุณ",
    sr_empty_title:  "ไม่พบรถยนต์",
    sr_clear_filters:"ล้างตัวกรอง",
    sr_vehicle:      "คัน",
    sr_vehicles:     "คัน",
    sr_for_sale:        "ขาย",
    sr_for_rent:        "เช่า",
    sr_details:         "รายละเอียด →",
    sr_add:             "+ เพิ่มรถ",
    sr_filters:         "ตัวกรอง",
    sr_sort:            "เรียงลำดับ",
    sr_sort_default:    "ค่าเริ่มต้น",
    sr_sort_price_low:  "ราคา: น้อย → มาก",
    sr_sort_price_high: "ราคา: มาก → น้อย",
    sr_sort_newest:     "ใหม่ที่สุดก่อน",
    sr_fuel:            "เชื้อเพลิง",
    sr_transmission:    "เกียร์",

    er_title:        "เช่ารถง่ายๆ",
    er_sub:          "เช่ารถได้ในไม่กี่ขั้นตอน",
    er_step:         "ขั้นตอน",
    er_step1_label:  "เลือกรถ",
    er_step2_label:  "สมัครสมาชิก",
    er_step3_label:  "จอง",
    er_rent_btn:     "เช่ารถ →",
    er_login_h:   "เข้าสู่ระบบหรือสร้างบัญชี",
    er_login_p:   "สร้างบัญชีด้วยเบอร์โทรหรืออีเมล",
    er_signup:    "คลิกเพื่อสมัครสมาชิก",
    er_logged:    "เข้าสู่ระบบแล้ว? ดำเนินการต่อได้เลย",
    er_next:      "ขั้นตอนถัดไป →",
    er_badge:     "• มีประกัน   • ผ่านการตรวจสอบ   • พร้อมใช้งาน",

    footer_tagline: "โชว์รูมรถที่คุณไว้วางใจในกรุงเทพ — รถคุณภาพ ราคาโปร่งใส",
    footer_hours:   "เปิดทุกวัน · 9:00 น. – 21:00 น.",
    footer_links:   "ลิงก์ด่วน",
    footer_contact: "ติดต่อเรา",
    footer_made:    "สร้างด้วยความรักที่กรุงเทพ ♥",
    footer_rights:  "© 2025 BKK Kaung Pyae Co., Ltd.",
    footer_home:    "หน้าหลัก",
    footer_shop:    "ร้าน",
    footer_brands:  "แบรนด์",
    footer_rental:  "เช่า",
    footer_about:   "เกี่ยวกับ",
  },
};

export const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    () => localStorage.getItem("bkk_lang") || "EN"
  );

  const changeLanguage = useCallback((lang) => {
    setLanguage(lang);
    localStorage.setItem("bkk_lang", lang);
  }, []);

  const t = useCallback(
    (key) => TRANSLATIONS[language]?.[key] ?? TRANSLATIONS.EN[key] ?? key,
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
